---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined
  tags:
    - always

- name: Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755
  tags:
    - always

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - always

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - always

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'
  tags:
    - always

# Setup/install redis.

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: restart redis
  tags:
    - redis

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
  tags:
    - redis

# Setup/install sentinel.

- name: Ensure Redis Sentinel is configured.
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    mode: "{{ redis_conf_mode }}"
    owner: "{{ redis_owner }}"
    group: "{{ redis_group }}"
  notify: restart sentinel
  tags:
    - sentinel
    - never

- name: Ensure Redis Sentinel service file.
  template:
    src: sentinel.service.j2
    dest: /etc/systemd/system/sentinel.service
    mode: "{{ redis_conf_mode }}"
  notify: restart sentinel
  tags:
    - sentinel
    - never

- name: Ensure Redis Sentinel working directory
  file:
    path: "{{ redis_sentinel_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ redis_owner }}"
    group: "{{ redis_group }}"
  notify: restart sentinel
  tags:
    - sentinel
    - never

- name: Ensure Redis Sentinel service file.
  template:
    src: sentinel.service.j2
    dest: /etc/systemd/system/sentinel.service
    mode: "{{ redis_conf_mode }}"
  notify: restart sentinel
  tags:
    - sentinel
    - never

- name: Ensure Redis Sentinel is running and enabled on boot.
  service: "name=sentinel state=started enabled=yes"
  tags:
    - sentinel
    - never

- name: Ensure Redis Sentinel is running and enabled on boot.
  service: "name=sentinel state=started enabled=yes"
  tags:
    - sentinel
    - never
